### ISSUE TITLE
How many blogs can a page hold

### ISSUE THREAD

**Issue by chanlovescindy** [NormandErwan/blogpaper#10]
Is the home page to a certain number of blogs, it will automatically pagination?

**Comment by NormandErwan** [comment]
There is an automatic pagination on the home page, and also on the categories and tags pages.

By default each page has 10 elements. You can change it on your [configuration](https://github.com/NormandErwan/Blogpaper#configure) with the `pagination` setting: <https://gohugo.io/getting-started/configuration/>.
