### ISSUE TITLE
Tag index page empty

### ISSUE THREAD

**Issue by ushandelucca** [NormandErwan/blogpaper#9]
When generating the website with Hugo version v0.68.3 (Ubuntu 20.04) the index page does not contain any tags. 
In other words: when I call the page www.mysite/tags, I get an empty page. With the Hugo version from Ubuntu 19.10 the index page was still generated correctly.

**Comment by NormandErwan** [comment]
Hi, thank you for pinpointing the issue!

I tested several versions, the tags page and the categories page get empty starting with Hugo v0.65.0
I don't get why. I'm going to investigate more.

**Comment by ushandelucca** [comment]
I guess that it has to do with the implementation of the "terms.html" template. In Blogpaper this file is absent.

**Comment by NormandErwan** [comment]
I finally took time to resolve the issue.

You're right, the `terms.html` template was missing. I added it and released a new version of the theme: [v1.0.2](https://github.com/NormandErwan/Blogpaper/releases/tag/v1.0.2).

Thank you!
